/*
	Strategy
	Authors: SeelingCat
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_MASINISSA_TECHS'		),
		('LEADER_CVS_MASINISSA_CIVICS'		),
		('LEADER_CVS_MASINISSA_DISCUSSIONS'	),
		('LEADER_CVS_MASINISSA_DISTRICTS'	),
		('LEADER_CVS_MASINISSA_BUILDINGS'	),
		('LEADER_CVS_MASINISSA_PROJECTS'	),
		('LEADER_CVS_MASINISSA_DIPLOMACY'	),
		('LEADER_CVS_MASINISSA_TACTICS'		),
		('LEADER_CVS_MASINISSA_EXPANSION'	),
		('LEADER_CVS_MASINISSA_PSUEDOS'		),
		('LEADER_CVS_MASINISSA_YIELDS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,								AgendaType,						System				)
VALUES  ('LEADER_CVS_MASINISSA_TECHS',			'TRAIT_AGENDA_CVS_MASINISSA',	'Technologies'		),
		('LEADER_CVS_MASINISSA_CIVICS',			'TRAIT_AGENDA_CVS_MASINISSA',	'Civics'			),
		('LEADER_CVS_MASINISSA_DISCUSSIONS',	'TRAIT_AGENDA_CVS_MASINISSA',	'Discussions'		),
		('LEADER_CVS_MASINISSA_DISTRICTS',		'TRAIT_AGENDA_CVS_MASINISSA',	'Districts'			),
		('LEADER_CVS_MASINISSA_BUILDINGS',		'TRAIT_AGENDA_CVS_MASINISSA',	'Buildings'			),
		('LEADER_CVS_MASINISSA_PROJECTS',		'TRAIT_AGENDA_CVS_MASINISSA',	'Projects'			),
		('LEADER_CVS_MASINISSA_DIPLOMACY',		'TRAIT_AGENDA_CVS_MASINISSA',	'DiplomaticActions'	),
		('LEADER_CVS_MASINISSA_TACTICS',		'TRAIT_AGENDA_CVS_MASINISSA',	'Tactics'			),
		('LEADER_CVS_MASINISSA_EXPANSION',		'TRAIT_AGENDA_CVS_MASINISSA',	'PlotEvaluations'	),
		('LEADER_CVS_MASINISSA_PSUEDOS',		'TRAIT_AGENDA_CVS_MASINISSA',	'PsuedoYields'		),
		('LEADER_CVS_MASINISSA_YIELDS',			'TRAIT_AGENDA_CVS_MASINISSA',	'Yields'			);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_MASINISSA_TECHS',		'TECH_IRRIGATION',						1		),
		('LEADER_CVS_MASINISSA_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_MASINISSA_TECHS',		'TECH_BANKING',							1		),
		('LEADER_CVS_MASINISSA_TECHS',		'TECH_ECONOMICS',						1		),
		('LEADER_CVS_MASINISSA_TECHS',		'TECH_BRONZE_WORKING',					1		),
		('LEADER_CVS_MASINISSA_TECHS',		'TECH_MILITARY_ENGINEERING',			1		),
		('LEADER_CVS_MASINISSA_TECHS',		'TECH_MILITARY_SCIENCE',				1		),
		-- CIVICS
		('LEADER_CVS_MASINISSA_CIVICS',		'CIVIC_MILITARY_TRAINING',				1		),
		('LEADER_CVS_MASINISSA_CIVICS',		'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_MASINISSA_CIVICS',		'CIVIC_MERCANTILISM',					1		),
		('LEADER_CVS_MASINISSA_CIVICS',		'CIVIC_DIPLOMATIC_SERVICE',				1		),
		('LEADER_CVS_MASINISSA_CIVICS',		'CIVIC_MOBILIZATION',					1		),
		-- DISTRICTS
		('LEADER_CVS_MASINISSA_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CVS_MASINISSA_DISTRICTS',	'DISTRICT_ENCAMPMENT',					1		),
		-- BUILDINGS
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_MARKET',						1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_BANK							1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_MILITARY_ACADEMY',			1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_ARMORY',						1		),
		-- WONDERS
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_BIG_BEN',						1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_PETRA',						1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_TERRACOTTA_ARMY',				1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_ALHAMBRA',					1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_ANGKOR_WAT',					1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_HANGING_GARDENS',				1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_MACHU_PICCHU',				1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_PYRAMIDS',					1		),
		('LEADER_CVS_MASINISSA_BUILDINGS',	'BUILDING_UNIVERSITY_SANKORE',			1		);

INSERT INTO AiFavoredItems
		(ListType,							Item,							Favored,	Value,	StringVal				)
VALUES  -- EXPANSION
		('LEADER_CVS_MASINISSA_PSUEDOS',	'Specific Feature',				1,			10,		'FEATURE_OASIS'			),
		('LEADER_CVS_MASINISSA_PSUEDOS',	'Specific Feature',				1,			5,		'FEATURE_FLODOPLAINS'	),
		-- PSUEDOS
		('LEADER_CVS_MASINISSA_PSUEDOS',	'PSEUDOYIELD_GPP_MERCHANT',		1,			50,		NULL					),
		('LEADER_CVS_MASINISSA_PSUEDOS',	'PSEUDOYIELD_GPP_GENERAL',		1,			50,		NULL					),
		('LEADER_CVS_MASINISSA_PSUEDOS',	'PSEUDOYIELD_UNIT_TRADE',		1,			50,		NULL					),
		('LEADER_CVS_MASINISSA_PSUEDOS',	'PSEUDOYIELD_UNIT_COMBAT',		1,			25,		NULL					),
		-- YIELDS
		('LEADER_CVS_MASINISSA_YIELDS',		'YIELD_GOLD',					1,			50,		NULL					);

