/*
	Strategy
	Authors: SeelingCat
*/

-----------------------------------------------
-- AiListTypes
-----------------------------------------------

INSERT INTO AiListTypes
		(ListType							)
VALUES 	('LEADER_CVS_TIN_HINAN_TECHS'		),
		('LEADER_CVS_TIN_HINAN_CIVICS'		),
		('LEADER_CVS_TIN_HINAN_DISCUSSIONS'	),
		('LEADER_CVS_TIN_HINAN_DISTRICTS'	),
		('LEADER_CVS_TIN_HINAN_BUILDINGS'	),
		('LEADER_CVS_TIN_HINAN_PROJECTS'	),
		('LEADER_CVS_TIN_HINAN_DIPLOMACY'	),
		('LEADER_CVS_TIN_HINAN_TACTICS'		),
		('LEADER_CVS_TIN_HINAN_EXPANSION'	),
		('LEADER_CVS_TIN_HINAN_PSUEDOS'		),
		('LEADER_CVS_TIN_HINAN_YIELDS'		);

-----------------------------------------------
-- AiLists
-----------------------------------------------

INSERT INTO AiLists
		(ListType,								AgendaType,						System				)
VALUES  ('LEADER_CVS_TIN_HINAN_TECHS',			'TRAIT_AGENDA_CVS_TIN_HINAN',	'Technologies'		),
		('LEADER_CVS_TIN_HINAN_CIVICS',			'TRAIT_AGENDA_CVS_TIN_HINAN',	'Civics'			),
		('LEADER_CVS_TIN_HINAN_DISCUSSIONS',	'TRAIT_AGENDA_CVS_TIN_HINAN',	'Discussions'		),
		('LEADER_CVS_TIN_HINAN_DISTRICTS',		'TRAIT_AGENDA_CVS_TIN_HINAN',	'Districts'			),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',		'TRAIT_AGENDA_CVS_TIN_HINAN',	'Buildings'			),
		('LEADER_CVS_TIN_HINAN_PROJECTS',		'TRAIT_AGENDA_CVS_TIN_HINAN',	'Projects'			),
		('LEADER_CVS_TIN_HINAN_DIPLOMACY',		'TRAIT_AGENDA_CVS_TIN_HINAN',	'DiplomaticActions'	),
		('LEADER_CVS_TIN_HINAN_TACTICS',		'TRAIT_AGENDA_CVS_TIN_HINAN',	'Tactics'			),
		('LEADER_CVS_TIN_HINAN_EXPANSION',		'TRAIT_AGENDA_CVS_TIN_HINAN',	'PlotEvaluations'	),
		('LEADER_CVS_TIN_HINAN_PSUEDOS',		'TRAIT_AGENDA_CVS_TIN_HINAN',	'PsuedoYields'		),
		('LEADER_CVS_TIN_HINAN_YIELDS',			'TRAIT_AGENDA_CVS_TIN_HINAN',	'Yields'			);
		
-----------------------------------------------
-- AiFavoredItems
-----------------------------------------------

INSERT INTO AiFavoredItems
		(ListType,							Item,									Favored	)
VALUES  -- TECHS
		('LEADER_CVS_TIN_HINAN_TECHS',		'TECH_IRRIGATION',						1		),
		('LEADER_CVS_TIN_HINAN_TECHS',		'TECH_CURRENCY',						1		),
		('LEADER_CVS_TIN_HINAN_TECHS',		'TECH_BANKING',							1		),
		('LEADER_CVS_TIN_HINAN_TECHS',		'TECH_ECONOMICS',						1		),
		-- CIVICS
		('LEADER_CVS_TIN_HINAN_CIVICS',		'CIVIC_GAMES_RECREATION',				1		),
		('LEADER_CVS_TIN_HINAN_CIVICS',		'CIVIC_FOREIGN_TRADE',					1		),
		('LEADER_CVS_TIN_HINAN_CIVICS',		'CIVIC_MERCANTILISM',					1		),
		('LEADER_CVS_TIN_HINAN_CIVICS',		'CIVIC_NATURAL_HISTORY',				1		),
		('LEADER_CVS_TIN_HINAN_CIVICS',		'CIVIC_PROFESSIONAL_SPORTS',			1		),
		-- DISTRICTS
		('LEADER_CVS_TIN_HINAN_DISTRICTS',	'DISTRICT_COMMERCIAL_HUB',				1		),
		('LEADER_CVS_TIN_HINAN_DISTRICTS',	'DISTRICT_ENTERTAINMENT_COMPLEX',		1		),
		-- BUILDINGS
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_MARKET',						1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_BANK							1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_STOCK_EXCHANGE',				1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_ARENA',						1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_ZOO',							1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_STADIUM',						1		),
		-- WONDERS
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_BIG_BEN',						1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_PETRA',						1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_COLOSSEUM',					1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_COLOSSUS',					1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_ESTADIO_DO_MARACANA',			1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_GOLDEN_GATE_BRIDGE',			1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_GREAT_ZIMBABWE',				1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_HANGING_GARDENS',				1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_MACHU_PICCHU',				1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_PYRAMIDS',					1		),
		('LEADER_CVS_TIN_HINAN_BUILDINGS',	'BUILDING_UNIVERSITY_SANKORE',			1		);

INSERT INTO AiFavoredItems
		(ListType,							Item,							Favored,	Value,	StringVal				)
VALUES  -- EXPANSION
		('LEADER_CVS_TIN_HINAN_PSUEDOS',	'Specific Feature',				1,			10,		'FEATURE_OASIS'			),
		('LEADER_CVS_TIN_HINAN_PSUEDOS',	'Specific Feature',				1,			5,		'FEATURE_FLODOPLAINS'	),
		-- PSUEDOS
		('LEADER_CVS_TIN_HINAN_PSUEDOS',	'PSEUDOYIELD_DIPLOMATIC_BONUS',	1,			10,		NULL					),
		('LEADER_CVS_TIN_HINAN_PSUEDOS',	'PSEUDOYIELD_GPP_MERCHANT',		1,			50,		NULL					),
		('LEADER_CVS_TIN_HINAN_PSUEDOS',	'PSEUDOYIELD_UNIT_TRADE',		1,			50,		NULL					),
		-- YIELDS
		('LEADER_CVS_TIN_HINAN_YIELDS',		'YIELD_GOLD',					1,			50,		NULL					);

